### ISSUE TITLE
Make Azure DevOps project public

### ISSUE THREAD

**Issue by xtellurian** [microsoft/azure-databricks-operator#22]
I'm opening this up for discussion.

What are the pro's and con's of making the Azure DevOps project (the one that is building the container images) public? [Read more about public projects here](https://docs.microsoft.com/en-us/azure/devops/organizations/public/make-project-public)

**Comment by xtellurian** [comment]
The current build is running in an organization that is inappropriate for a public project. We are looking into migrating to an appropriate Azure DevOps org.

**Comment by Azadehkhojandi** [comment]
the pipelines are public and can be accessed here > https://dev.azure.com/ms/azure-databricks-operator
